### PR TITLE
ci: merge with actual parent branch (not necessarily master)

### PR DESCRIPTION
**Pull request by kierdavis**
See also: https://github.com/j5api/j5/pull/413

### CODE REVIEW

**Comment by trickeydan** [comment]
We need to add a GitHub API token to the environment variables in circle CI.

See circleci_branch for details

**Comment by kierdavis** [comment]
How did you generate the token for j5? Is it attached to your personal account or a shared account, or neither?

**Comment by trickeydan** [comment]
It's attached to j5bot. It doesn't have any special privileges though

**Comment by trickeydan** [comment]
I've added a token and retriggered the jobs.

**Pull request merged**
