### PR TITLE
Optional singular

### PR DESCRIPTION
**Pull request by kierdavis**
Add ability to not require all boards to be connected

Useful for development where not having a motor board connected
is not considered an error.

### CODE REVIEW

**Comment by kierdavis** [comment]
What logging could be added that isn't already covered by `_dump_boards`?

Unrelated: I think I might rename that function to `_log_boards` for clarity.

**Comment by kierdavis** [comment]
Tests failing due to using an old version of j5 - it needs https://github.com/j5api/j5/commit/40467977fae1476b35c153553131671d65e9163f which has not made it into a j5 release yet.

**Comment by trickeydan** [comment]
> Typechecking failing due to using an old version of j5 - it needs [j5api/j5@4046797](https://github.com/j5api/j5/commit/40467977fae1476b35c153553131671d65e9163f) which has not made it into a j5 release yet.

Alright, I'm happy to see a minor release of `j5` to help with this. There have been 87 commits to master since `0.4.0`

**Comment by kierdavis** [comment]
Sounds good to me.

**Pull request merged**
